name: dribbble_client
description: A Dribbble Api client for Dart
version: 0.0.2
homepage: https://github.com/brianegan/dribbble_client
author: Brian Egan <brian@brianegan.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  http: '>=0.11.3+14 <0.12.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  http_mock: '>=1.0.0 <2.0.0'
